train_path: ./train_data
val_path: ./val_data
test_path: ./test_data
save_path: runs\trial_0000\best_model.pth
submission_path: ./submission.csv
model_name: efficientnet_b4
image_size: 380
pretrained: true
use_gradient_checkpointing: true
drop_rate: 0.519705687464961
drop_path_rate: 0.18033450352296262
batch_size: 64
epochs: 5
seed: 42
device_str: cuda
num_workers: 12
pin_memory: true
shuffle: true
drop_last: false
persistent_workers: false
prefetch_factor: 4
optimizer_cls: AdamW
optimizer_params:
  lr: 5.6115164153345e-05
  weight_decay: 0.0022648248189516837
scheduler_cls: CosineAnnealingLR
scheduler_params:
  T_max: 20
  eta_min: 1.0e-06
criterion_cls: BCEWithLogitsLoss
criterion_params:
  pos_weight: null
p_horizontal_flip: 0.5
p_random_rotate90: 0.5
p_transpose: 0.2
use_default_transform: true
patience: 10
min_delta: 0.0
mode: max
verbose: true
